/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.uricer.view;

/**
 *
 * @author renan
 */
public class PrincipalForm extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalForm
     */
    public PrincipalForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        Cadastro = new javax.swing.JMenu();
        mnCadastroProduto = new javax.swing.JMenuItem();
        mnCadastroFornecedor = new javax.swing.JMenuItem();
        mnCadastroCliente = new javax.swing.JMenuItem();
        Editar = new javax.swing.JMenu();
        mnEditarProduto = new javax.swing.JMenuItem();
        mnEditarFornecedor = new javax.swing.JMenuItem();
        mnEditarCliente = new javax.swing.JMenuItem();
        Pesquisar = new javax.swing.JMenu();
        mnPesquisarProduto = new javax.swing.JMenuItem();
        mnPesquisarFornecedor = new javax.swing.JMenuItem();
        mnPesquisarCliente = new javax.swing.JMenuItem();
        Excluir = new javax.swing.JMenu();
        mnExcluirProduto = new javax.swing.JMenuItem();
        mnExcluirFornecedor = new javax.swing.JMenuItem();
        mnExcluirCliente = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Vendas");

        Cadastro.setText("Cadastro");

        mnCadastroProduto.setText("Produto");
        mnCadastroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadastroProdutoActionPerformed(evt);
            }
        });
        Cadastro.add(mnCadastroProduto);

        mnCadastroFornecedor.setText("Fornecedor");
        mnCadastroFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadastroFornecedorActionPerformed(evt);
            }
        });
        Cadastro.add(mnCadastroFornecedor);

        mnCadastroCliente.setText("Cliente");
        mnCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadastroClienteActionPerformed(evt);
            }
        });
        Cadastro.add(mnCadastroCliente);

        jMenuBar1.add(Cadastro);

        Editar.setText("Editar");

        mnEditarProduto.setText("Produto");
        Editar.add(mnEditarProduto);

        mnEditarFornecedor.setText("Fornecedor");
        Editar.add(mnEditarFornecedor);

        mnEditarCliente.setText("Cliente");
        Editar.add(mnEditarCliente);

        jMenuBar1.add(Editar);

        Pesquisar.setText("Pesquisar");

        mnPesquisarProduto.setText("Produto");
        Pesquisar.add(mnPesquisarProduto);

        mnPesquisarFornecedor.setText("Fornecedor");
        mnPesquisarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPesquisarFornecedorActionPerformed(evt);
            }
        });
        Pesquisar.add(mnPesquisarFornecedor);

        mnPesquisarCliente.setText("Cliente");
        Pesquisar.add(mnPesquisarCliente);

        jMenuBar1.add(Pesquisar);

        Excluir.setText("Excluir");

        mnExcluirProduto.setText("Produto");
        Excluir.add(mnExcluirProduto);

        mnExcluirFornecedor.setText("Fornecedor");
        Excluir.add(mnExcluirFornecedor);

        mnExcluirCliente.setText("Cliente");
        Excluir.add(mnExcluirCliente);

        jMenuBar1.add(Excluir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadastroClienteActionPerformed
        // TODO add your handling code here:
        new CadastroClienteForm().setVisible(true);
    }//GEN-LAST:event_mnCadastroClienteActionPerformed

    private void mnPesquisarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPesquisarFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnPesquisarFornecedorActionPerformed

    private void mnCadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadastroProdutoActionPerformed
        // TODO add your handling code here:
        new CadastroProdutoForm().setVisible(true);
    }//GEN-LAST:event_mnCadastroProdutoActionPerformed

    private void mnCadastroFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadastroFornecedorActionPerformed
        // TODO add your handling code here:
        new CadastroFornecedorForm().setVisible(true);
    }//GEN-LAST:event_mnCadastroFornecedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Cadastro;
    private javax.swing.JMenu Editar;
    private javax.swing.JMenu Excluir;
    private javax.swing.JMenu Pesquisar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnCadastroCliente;
    private javax.swing.JMenuItem mnCadastroFornecedor;
    private javax.swing.JMenuItem mnCadastroProduto;
    private javax.swing.JMenuItem mnEditarCliente;
    private javax.swing.JMenuItem mnEditarFornecedor;
    private javax.swing.JMenuItem mnEditarProduto;
    private javax.swing.JMenuItem mnExcluirCliente;
    private javax.swing.JMenuItem mnExcluirFornecedor;
    private javax.swing.JMenuItem mnExcluirProduto;
    private javax.swing.JMenuItem mnPesquisarCliente;
    private javax.swing.JMenuItem mnPesquisarFornecedor;
    private javax.swing.JMenuItem mnPesquisarProduto;
    // End of variables declaration//GEN-END:variables
}
