/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  renan
 * Created: 24/11/2016
 */

create table clientes (id integer generated by default as identity primary key,
nome varchar(255),
cidade varchar(255));
create table fornecedores (id integer generated by default as identity primary key,
nome varchar(255),
cidade varchar(255));
create table produtos (id integer generated by default as identity primary key,
nome varchar(255),
preco_venda numeric(10,2),
preco_custo numeric(10,2));
create table Vendas (id integer generated by default as identity primary key,
id_cli integer,
id_prod integer,
id_fornec integer,
valor_venda numeric(10,2));

Alter Table vendas
Add FOREIGN KEY (id_cli)
References clientes (id); 

Alter Table vendas
Add FOREIGN KEY (id_prod)
References produtos (id); 

Alter Table vendas
Add FOREIGN KEY (id_fornec)
References fornecedores (id); 


